from django.urls import path, include
from banner.views import MyObtainTokenPairView, RegisterView
from rest_framework_simplejwt.views import TokenRefreshView
from django.conf.urls import include, url
from . import views

urlpatterns = [
    path('login/', MyObtainTokenPairView.as_view(), name='token_obtain_pair'),
    # path('Categoryapi/', Categoryapi.as_view(), name='Categoryapi'),
    # path('Productapi/', Productapi.as_view(), name='Productapi'),
    path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='auth_register'),
    # path("<phone>/", getPhoneNumberRegistered.as_view(), name="OTP Gen"),
    path('add_banner/', views.add_banner, name="Add Banner"),
    path('banner_list/', views.banner_list, name="Show All Banner"),
    path('banner_list_client/', views.banner_list_client, name="Show All Banner"),
    path('banner_edit/<int:pk>/', views.banner_edit, name="Edit Banner"),
    path('banner_delete/<int:pk>/', views.banner_delete, name="Delete Banner"),
    path('add_category/', views.add_category, name="Add Category"),
    path('category_list/', views.category_list, name="Show All Category"),
    path('show_category/', views.show_category, name="Show All Category"),
    path('user_login/', views.user_login, name="login"),
    path('admin_login/', views.admin_login, name="Admin Login"),
    path('auth_otp/', views.auth_otp, name="auth otp"),
    path('show_user/', views.show_user, name="show_user"),
    path('create_bitly/', views.create_bitly, name="Test"),
    path('category_delete/', views.category_delete, name="Delete Category"),
    path('update_profile/', views.update_profile, name="Edit Profile"),
    path('add_products/', views.add_products, name="Add Products"),
    path('product_edit/', views.product_edit, name="Edit Products"),
    path('products_list/', views.products_list, name="Show all Products"),
    path('product_delete/', views.product_delete, name="Delete Products"),
    path('add_to_cart/', views.add_to_cart, name="Add to cart"),
    path('show_cart/', views.show_cart, name="Show cart"),
    path('edit_cart/', views.edit_cart, name="Edit cart"),
    path('show_orders/', views.show_orders, name="Orders"),
    path('check_token/', views.check_token, name="check_token"),
    path('add_coupon/', views.add_coupon, name="add_coupon"),
    path('apply_coupon/', views.apply_coupon, name="apply_coupon"),
    path('delete_coupon/', views.delete_coupon, name="Delete Coupon"),
    path('add_address/', views.add_address, name="Add Address"),
    path('show_address/', views.show_address, name="Show Address"),
    path('show_orders_admin/', views.show_orders_admin, name="Show Order Admin"),
    path('edit_order/', views.edit_order, name="Edit Order Admin"),
    path('cancel_order/', views.cancel_order, name="Cancel Order"),
    path('edit_address/', views.edit_address, name="Edit Address"),
    path('delete_address/', views.delete_address, name="Delete Address"),
    path('checkout/', views.checkout, name="Checkout"),
    path('test_payment/', views.test_payment, name="Payment"),
    path('save_stripe_info/', views.save_stripe_info, name="Payment"),
    path('add_dinein/', views.add_dinein, name="Add Dine"),
    path('edit_dinein/', views.edit_dinein, name="Edit Dine"),
    path('show_dinein/', views.show_dinein, name="Show Dine"),
    path('delete_dinein/', views.delete_dinein, name="Delete Dine"),
    path('add_booking/', views.add_booking, name="Add Booking"),
    path('show_booking/', views.show_booking, name="Show Booking"),
    path('show_booking_admin/', views.show_booking_admin, name="show_booking_admin"),
    path('add_review/', views.add_review, name="add_review"),
    path('edit_review/', views.edit_review, name="edit_review"),
    path('show_review/', views.show_review, name="show_review"),
    path('delete_review/', views.delete_review, name="delete_review"),
    # path('category_edit/<int:pk>/', views.category_edit, name="Edit Category"),
    url(r'^category_edit/(?P<pk>\d+)/', views.category_edit, name='Edit Category'),
    # path("time_based/<phone>/", getPhoneNumberRegistered_TimeBased.as_view(), name="OTP Gen Time Based"),
]


