# Generated by Django 3.2.6 on 2021-08-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20210826_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
