# Generated by Django 3.2.6 on 2021-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20210830_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('type', models.BooleanField(default=False)),
                ('discription', models.CharField(blank=True, max_length=1000)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav', models.BooleanField(default=False)),
            ],
        ),
    ]
