# Generated by Django 3.2.6 on 2021-09-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_alter_products_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
