# Generated by Django 3.2.6 on 2021-09-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.category'),
        ),
    ]
