# Generated by Django 3.2.6 on 2021-09-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_alter_products_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='category_name',
            new_name='name',
        ),
    ]
