# Generated by Django 3.2.6 on 2021-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_alter_products_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='unit_price',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
