# Generated by Django 3.2.6 on 2021-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_auto_20210904_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
