# Generated by Django 3.2.6 on 2021-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_auto_20210904_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
