# Generated by Django 3.2.6 on 2021-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_auto_20210904_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
