# Generated by Django 3.2.6 on 2021-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0021_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(blank=True, max_length=100)),
                ('expire_date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('discount', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
