# Generated by Django 3.2.6 on 2021-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0023_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
