# Generated by Django 3.2.6 on 2021-09-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0024_alter_offers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
