# Generated by Django 3.2.6 on 2021-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0027_auto_20210918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
