# Generated by Django 3.2.6 on 2021-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0028_alter_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
